### ISSUE TITLE
/api/mine/book_stacks 返回 401 错误

### ISSUE THREAD

**Issue by InspAlgo** [renyunkang/yuque-exporter#19]
<img width="946" alt="PixPin_2024-06-17_22-55-48" src="https://github.com/renyunkang/yuque-exporter/assets/30190529/c79ab58a-d812-4677-996f-f3ed4da33106">

使用时发现 Books count 这里显示为 0，看了下 /api/mine/book_stacks 接口此时返回 401 错误。

怀疑是少了某个请求头参数，于是添加了几个参数，但也没有生效。

<img width="655" alt="PixPin_2024-06-17_23-00-09" src="https://github.com/renyunkang/yuque-exporter/assets/30190529/d317ed29-d52c-4a6e-bcda-8dba982cdf5b">

**Comment by renyunkang** [comment]
用 F12 看下你的账号是调用的哪一个接口，我看了下我的个人账号还是这个接口且数据正常返回

**Comment by InspAlgo** [comment]
> 用 F12 看下你的账号是调用的哪一个接口，我看了下我的个人账号还是这个接口且数据正常返回

感谢，问题解决了，是我的使用错误，该 issue 关闭。

几个月前 USER 填的手机号登录过，保留了 cookie，这次 USER 用的是用户名，但登录仍然使用的是旧 cookie。把旧 cookie 清掉，USER 还是用手机号，重新试了下就可以了。

又看了下官网，发现官网现在只能手机号登录，印象中以前是允许用户名登录的（：
