### ISSUE TITLE
MacOS env configuration

### ISSUE THREAD

**Issue by rookieuncle** [renyunkang/yuque-exporter#6]
For README.md, it is recommended to add MacOS environment variable configuration. I can provide it

**Comment by renyunkang** [comment]
Thank you for offering to contribute the MacOS environment variable configuration! I would warmly welcome a Pull Request (PR) from you. Your addition would make it easier for more people to set up their MacOS environment. If you need any guidance or assistance, please let me know. Thanks!

**Comment by renyunkang** [comment]
pr: https://github.com/renyunkang/yuque-exporter/pull/7
